/**
 * PrintTheShot — 内置文案表 / built-in string table
 * =================================================
 *
 * 中文
 * ----
 * 这份表是界面文案的**底线**,不是全部。
 *
 * 桌面浏览器里,index.html 和 app.js 由 Python 服务端发出去,服务端会把
 * {{LANG}} 占位符替换成当前语言的完整文案表(含 AI 新增的自定义语言)——
 * 那条路径下这份表基本用不上。
 *
 * 但在 Android 上,Web UI 是**打包进 APK** 的,文件原样复制,没有任何服务端
 * 参与替换,{{LANG}} 会原样留在 app.js 里。而 JSON.parse('{{LANG}}') 在第一行
 * 就抛异常,整个脚本加载失败 —— 界面直接白屏,且不报任何看得见的错。
 *
 * 所以界面文案必须自带一份。服务端注入的表如果存在,会覆盖在这份之上。
 *
 * English
 * -------
 * This table is the **floor** for UI strings, not the whole story.
 *
 * In a desktop browser, index.html and app.js are served by the Python service,
 * which substitutes the {{LANG}} placeholder with the full table for the current
 * language (including custom AI-translated ones) — on that path this table is
 * mostly unused.
 *
 * On Android, though, the web UI is **bundled inside the APK**. The files are
 * copied verbatim, nothing substitutes anything, and {{LANG}} stays in app.js —
 * where JSON.parse('{{LANG}}') throws on the very first line, the whole script
 * fails to load, and the app shows a blank screen with no visible error.
 *
 * So the strings have to ship with the UI. Any server-injected table is layered
 * on top of this one.
 *
 * 由 scripts/export_strings.py 从 print_the_shot_server.py 的 LANGUAGES 表导出,
 * 改文案请改那边再重新导出 —— 不要两边各改一份。
 * Generated from the LANGUAGES table in print_the_shot_server.py. Edit there and
 * re-run the exporter rather than keeping two hand-maintained copies.
 */

window.PTS_VERSION = "2.1-beta.3";

window.PTS_STRINGS = {
  "en": {
    "active_users": "Active Users",
    "ai_enabled_label": "Enable AI translation for bean info (timeout falls back to original text)",
    "ai_key_hint": "enter API key",
    "ai_key_saved": "API key saved",
    "ai_lang_hint": "language name required",
    "ai_toggled": "AI translation setting saved",
    "ai_translating": "Translating UI strings via AI, ~10-30s...",
    "all_dates": "All dates",
    "bean_info_enabled": "Bean Info Enabled",
    "bt_android_only": "Bluetooth printing is Android-only",
    "bt_connect": "Connect",
    "bt_connect_fail": "Connection failed",
    "bt_connect_ok": "Connected",
    "bt_connected": "Connected",
    "bt_connecting": "Connecting…",
    "bt_denied": "Permission denied — grant Bluetooth access in Android settings",
    "bt_disconnect": "Disconnect",
    "bt_empty": "No paired printers yet. Pair the printer in Android Settings → Bluetooth first.",
    "bt_empty_hint": "If the printer is already paired, Bluetooth permission is probably missing.",
    "bt_granted": "Permission granted",
    "bt_none": "No printer selected",
    "bt_reconnect": "Reconnect",
    "bt_refresh": "Refresh list",
    "bt_request": "Grant permission",
    "bt_requesting": "Requesting permission…",
    "bt_saved_not_connected": "Selected, not connected",
    "bt_scanning": "Loading paired devices…",
    "bt_status_label": "Connection",
    "bt_test": "Test print",
    "bt_test_fail": "Test print failed",
    "bt_test_ok": "Test page sent — check the printer",
    "bt_testing": "Sending a test page…",
    "bt_title": "Bluetooth printer",
    "bt_unpaired": "not paired",
    "btn_add_lang": "Add Language",
    "btn_check_balance": "Check Balance",
    "btn_check_update": "Check for updates",
    "btn_save_key": "Save API Key",
    "btn_shutdown": "Stop service",
    "btn_translate": "Translate this chart with AI",
    "btn_update_service": "Update service from GitHub (auto backup)",
    "capped_note": "Too many shots — showing latest 100. Please filter by date.",
    "chart_bean_info": "Bean Info",
    "chart_coffee_flow": "Coffee Flow",
    "chart_date_time": "Date&Time",
    "chart_extraction": "Extraction",
    "chart_flow": "Flow Rate (g/s)",
    "chart_grind_setting": "Grind",
    "chart_grinder_temp": "Grind&Temp",
    "chart_in_weight": "In",
    "chart_initial_temp": "Temp",
    "chart_na": "N/A",
    "chart_out_weight": "Out",
    "chart_pressure": "Pressure (Bar)",
    "chart_profile": "Profile",
    "chart_profile_info": "Profile Info",
    "chart_shot_time": "Time",
    "chart_tasting_note": "Tasting Note",
    "chart_temperature": "Temp (°C)",
    "chart_time": "Time (s)",
    "chart_unknown_profile": "Unknown Profile",
    "chart_water_flow": "Water Flow",
    "clear_queue": "Clear Queue",
    "data_upload": "Data Upload",
    "disable_bean_info": "Disable Bean Info",
    "disable_print": "Disable Printing",
    "drag_drop": "Drag and drop JSON file here or click to select",
    "enable_bean_info": "Enable Bean Info",
    "enable_print": "Enable Printing",
    "h_ai_settings": "AI Translation and Languages",
    "h_languages": "Languages:",
    "h_print": "Printing",
    "h_stats": "Statistics",
    "keepalive_hint": "Keeps the server and printing alive while another app is in the foreground",
    "keepalive_label": "Background keep-alive",
    "keepalive_off": "Off",
    "keepalive_on": "Running",
    "keepalive_turn_off": "Turn off",
    "keepalive_turn_on": "Turn on",
    "lan_address_hint": "Use this as the server address in the DE1 plugin",
    "lan_address_label": "Device address",
    "language": "Language",
    "latest_n": "Latest 9",
    "machine_id": "",
    "max_users": "Max Users",
    "next_day": "Next day",
    "no_data": "No data available",
    "per_page": "per page",
    "plugin_download": "Download DE1 Plugin",
    "plugin_github": "Download from GitHub (latest)",
    "plugin_instructions": "Plugin Installation",
    "plugin_local": "Download plugin (local · matches this version)",
    "plugin_note": "The local plugin matches this server version; the GitHub one may be newer.",
    "plugin_step1": "Download plugin.tcl and copy it to the DE1 tablet:",
    "plugin_step2": "/de1plus/plugins/print_the_shot/plugin.tcl",
    "plugin_step3": "Restart DE1App — the plugin loads automatically",
    "plugin_step4": "Server address: {HOST}, path: upload",
    "plugin_step4_fallback": "this machine's IP:8000",
    "plugin_txt": "Download TXT (for Bluetooth send)",
    "prev_day": "Prev day",
    "print": "Print",
    "print_control": "Print Control",
    "print_default": "System default",
    "print_disabled": "Printing disabled",
    "print_enabled": "Printing Enabled",
    "print_job_sent": "Print job sent",
    "print_mode": "Mode",
    "print_platform": "Platform",
    "print_printer": "Printer",
    "print_queue": "Print Queue",
    "print_saved": "Print settings saved",
    "print_transport": "Transport",
    "print_width": "Width",
    "queue_empty": "Queue is empty",
    "queue_status": "Queue Status: {count} jobs",
    "recent_data": "Recently Received Data",
    "refresh": "Refresh",
    "server_title": "PrintTheShot Next Server v{VERSION}",
    "setup_connect": "Connect",
    "setup_failed": "Could not reach the server.",
    "setup_hint": "Enter the address of the PrintTheShot server on your network (the machine running print_the_shot_server.py).",
    "setup_ok": "Connected — server v{v}",
    "setup_prompt": "Server address (host:port)",
    "setup_required": "Please enter an address",
    "setup_testing": "Testing the connection…",
    "setup_title": "Connect to the server",
    "shots_received": "Shots Received",
    "show_latest_9": "Showing the latest 9 shots. Use date filter for the full day.",
    "shutdown_confirm": "Stop the PrintTheShot service? The web interface will become unavailable and you will need to start the app again.",
    "shutdown_denied": "Shutdown is not allowed from this address",
    "shutdown_failed": "Could not stop the service",
    "shutdown_ok": "Service stopped",
    "shutdown_sent": "Stopping… this page will stop responding.",
    "start_time": "Start Time",
    "stat_ai_balance": "AI Balance",
    "stat_avg_day": "avg {n}/day",
    "stat_avg_size": "Avg Data Size",
    "stat_beans": "Bean Distribution",
    "stat_dates": "Days",
    "stat_machines": "Machines",
    "stat_older": "{n} earlier days",
    "stat_per_date": "By Date",
    "stat_prints": "Prints (session)",
    "stat_profiles": "Top Profiles",
    "stat_total": "Total Shots",
    "status_running": "Running",
    "t_title": "Translate this chart into...",
    "total_n": "Total {n}",
    "translate_done": "Translated and re-rendered",
    "update_avail": "Update available",
    "update_check": "Local {local} · Remote {remote}",
    "update_note": "Auto-backup to backup/ before updating; restart the server after update; packaged builds can't self-update.",
    "update_ok": "Up to date",
    "update_title": "Service Update",
    "upload_failed": "Upload failed — check the server address and that the server is running.",
    "upload_success": "Upload successful",
    "view_large": "Click to view large image"
  },
  "zh": {
    "active_users": "并发用户",
    "ai_enabled_label": "启用 AI 翻译豆子信息(超时自动回退原文)",
    "ai_key_hint": "请输入 API Key",
    "ai_key_saved": "API Key 已保存",
    "ai_lang_hint": "请输入语言名称",
    "ai_toggled": "AI 翻译设置已保存",
    "ai_translating": "AI 正在翻译界面文案,约需 10-30 秒...",
    "all_dates": "全部日期",
    "bean_info_enabled": "豆子信息已启用",
    "bt_android_only": "蓝牙打印仅在 Android 上可用",
    "bt_connect": "连接",
    "bt_connect_fail": "连接失败",
    "bt_connect_ok": "已连接",
    "bt_connected": "已连接",
    "bt_connecting": "正在连接…",
    "bt_denied": "权限被拒绝 —— 请到 Android 设置里授予蓝牙权限",
    "bt_disconnect": "断开连接",
    "bt_empty": "还没有配对的打印机。请先在 Android 设置 → 蓝牙里配对打印机。",
    "bt_empty_hint": "如果打印机已经配对过了,那多半是蓝牙权限没给。",
    "bt_granted": "权限已授予",
    "bt_none": "尚未选择打印机",
    "bt_reconnect": "重新连接",
    "bt_refresh": "刷新列表",
    "bt_request": "申请权限",
    "bt_requesting": "正在申请权限…",
    "bt_saved_not_connected": "已选择,未连接",
    "bt_scanning": "正在读取已配对设备…",
    "bt_status_label": "连接状态",
    "bt_test": "测试打印",
    "bt_test_fail": "测试打印失败",
    "bt_test_ok": "测试页已发送 —— 看看打印机",
    "bt_testing": "正在发送测试页…",
    "bt_title": "蓝牙打印机",
    "bt_unpaired": "未配对",
    "btn_add_lang": "新增语言",
    "btn_check_balance": "查余额",
    "btn_check_update": "检查更新",
    "btn_save_key": "保存 API Key",
    "btn_shutdown": "停止服务",
    "btn_translate": "AI 翻译本条曲线",
    "btn_update_service": "从 GitHub 更新服务(自动备份)",
    "capped_note": "数据较多,仅显示最近 100 条,建议按日期筛选",
    "chart_bean_info": "咖啡豆信息",
    "chart_coffee_flow": "咖啡流速",
    "chart_date_time": "日期时间",
    "chart_extraction": "萃取参数",
    "chart_flow": "流速 (克/秒)",
    "chart_grind_setting": "研磨度",
    "chart_grinder_temp": "研磨与温度",
    "chart_in_weight": "咖啡粉",
    "chart_initial_temp": "温度",
    "chart_na": "未记录",
    "chart_out_weight": "咖啡液",
    "chart_pressure": "压力 (巴)",
    "chart_profile": "冲煮方案",
    "chart_profile_info": "冲煮方案信息",
    "chart_shot_time": "时间",
    "chart_tasting_note": "品鉴感受",
    "chart_temperature": "温度 (°C)",
    "chart_time": "时间 (秒)",
    "chart_unknown_profile": "未知方案",
    "chart_water_flow": "水流流速",
    "clear_queue": "清空队列",
    "data_upload": "数据上传",
    "disable_bean_info": "禁用豆子信息",
    "disable_print": "禁用打印",
    "drag_drop": "拖放JSON文件到这里或点击选择",
    "enable_bean_info": "启用豆子信息",
    "enable_print": "启用打印",
    "h_ai_settings": "AI 翻译与语言",
    "h_languages": "语言:",
    "h_print": "打印",
    "h_stats": "统计数据",
    "keepalive_hint": "让服务端和打印在别的应用位于前台时继续工作",
    "keepalive_label": "后台常驻",
    "keepalive_off": "已关闭",
    "keepalive_on": "运行中",
    "keepalive_turn_off": "关闭",
    "keepalive_turn_on": "开启",
    "lan_address_hint": "把它填进 DE1 插件的服务端地址",
    "lan_address_label": "本机地址",
    "language": "语言",
    "latest_n": "最新 9 条",
    "machine_id": "",
    "max_users": "最大用户",
    "next_day": "后一天",
    "no_data": "暂无数据",
    "per_page": "每页",
    "plugin_download": "下载DE1插件",
    "plugin_github": "从 GitHub 下载(最新)",
    "plugin_instructions": "插件安装",
    "plugin_local": "下载插件(本地·匹配当前版本)",
    "plugin_note": "本地插件与当前服务器版本匹配;GitHub 上的可能更新。",
    "plugin_step1": "下载 plugin.tcl 并复制到 DE1 平板:",
    "plugin_step2": "/de1plus/plugins/print_the_shot/plugin.tcl",
    "plugin_step3": "重启 DE1App,插件自动加载",
    "plugin_step4": "服务器地址填 {HOST},path 路径填写 upload",
    "plugin_step4_fallback": "本机IP:8000",
    "plugin_txt": "下载 TXT 版(蓝牙发送)",
    "prev_day": "前一天",
    "print": "打印",
    "print_control": "打印控制",
    "print_default": "系统默认",
    "print_disabled": "打印已禁用",
    "print_enabled": "打印已启用",
    "print_job_sent": "打印任务已发送",
    "print_mode": "模式",
    "print_platform": "平台",
    "print_printer": "打印机",
    "print_queue": "打印队列",
    "print_saved": "打印设置已保存",
    "print_transport": "通道",
    "print_width": "宽度",
    "queue_empty": "队列为空",
    "queue_status": "打印队列: {count} 个任务",
    "recent_data": "最近接收的数据",
    "refresh": "刷新",
    "server_title": "PrintTheShot Next 服务器 v{VERSION}",
    "setup_connect": "连接",
    "setup_failed": "连不上服务端。",
    "setup_hint": "填写局域网里 PrintTheShot 服务端的地址(也就是跑 print_the_shot_server.py 的那台机器)。",
    "setup_ok": "已连接 — 服务端 v{v}",
    "setup_prompt": "服务端地址(主机:端口)",
    "setup_required": "请填写地址",
    "setup_testing": "正在测试连接…",
    "setup_title": "连接服务端",
    "shots_received": "接收数据",
    "show_latest_9": "显示最新 9 条,按日期筛选可查看当日全部",
    "shutdown_confirm": "确定要停止 PrintTheShot 服务吗?管理界面将不可用,需要重新启动应用才能恢复。",
    "shutdown_denied": "不允许从该地址停止服务",
    "shutdown_failed": "停止失败",
    "shutdown_ok": "服务已停止",
    "shutdown_sent": "正在停止…本页面将不再响应。",
    "start_time": "启动时间",
    "stat_ai_balance": "AI 余额",
    "stat_avg_day": "日均 {n}",
    "stat_avg_size": "平均数据大小",
    "stat_beans": "豆子分布",
    "stat_dates": "数据天数",
    "stat_machines": "机器数",
    "stat_older": "更早 {n} 天",
    "stat_per_date": "按日期分布",
    "stat_prints": "打印次数(本次运行)",
    "stat_profiles": "Top 冲煮方案",
    "stat_total": "总接收数据",
    "status_running": "运行中",
    "t_title": "翻译本条曲线为...",
    "total_n": "共 {n} 条",
    "translate_done": "已翻译并重新渲染",
    "update_avail": "有更新可用",
    "update_check": "当前 {local} · 远程 {remote}",
    "update_note": "更新前自动备份到 backup/ 目录;更新后请重启服务器;打包版不支持在线更新。",
    "update_ok": "已是最新",
    "update_title": "服务更新",
    "upload_failed": "上传失败 —— 请检查服务端地址,以及服务端是否在运行。",
    "upload_success": "上传成功",
    "view_large": "点击查看大图"
  }
};
